{% set name = "txtai" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txtai-{{ version }}.tar.gz
  sha256: 89835840f4c634e95d754533f39d0737532259540c02abfdd0340e23e4ef4149

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - faiss-cpu >=1.7.1.post2
    - pytorch >=1.12.1
    - transformers >=4.22.0

    - huggingface_hub >=0.9.0
    - numpy >=1.18.4
    - pyyaml >=5.3
    - regex >=2022.8.17

test:
  imports:
    - txtai

about:
  home: https://neuml.github.io/txtai
  dev_url: https://github.com/neuml/txtai
  summary: Build AI-powered semantic search applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
