{% set name = "txtai" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txtai-{{ version }}.tar.gz
  sha256: 0c71bece7de6d91672ed11200be118b152ea152d4090cfa48c9fb00a68a01737

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - faiss-cpu >=1.7.1.post2
    - numpy >=1.18.4
    - pyyaml >=5.3
    - pytorch >=1.6.0
    - transformers >=4.22.0

test:
  imports:
    - txtai

about:
  home: https://neuml.github.io/txtai
  dev_url: https://github.com/neuml/txtai
  summary: Build AI-powered semantic search applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
