schema_version: 1

context:
  name: txtai
  version: "9.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/txtai-${{ version }}.tar.gz
  sha256: 8270791cd1b8be37210adc44f72b8209ce0fe753ebb385c2784a713b1d01b11a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - faiss-cpu >=1.7.1.post2
    - msgpack-python >=1.0.7
    - pytorch >=2.4
    - transformers >=4.56.2
    - huggingface_hub >=0.34.0
    - numpy >=1.18.4
    - pyyaml >=5.3
    - regex >=2022.8.17
    - safetensors >=0.4.5
    # Try
    - accelerate
    - tqdm >=4.67.0

tests:
  - python:
      imports:
        - txtai
      # turn off pip check as it does not work with faiss-cpu
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Build AI-powered semantic search applications
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://neuml.github.io/txtai
  repository: https://github.com/neuml/txtai

extra:
  recipe-maintainers:
    - thewchan
