schema_version: 1

context:
  name: txtai
  version: 8.5.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/txtai-${{ version }}.tar.gz
  sha256: 4f3d7815607db486c8a74b3646609ff11d9a8710a6490952f90012246e7e2f03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - faiss-cpu >=1.7.1.post2
    - msgpack-python >=1.0.7
    - pytorch >=1.12.1
    - transformers >=4.45.0
    - huggingface_hub >=0.19.0
    - numpy >=1.18.4
    - pyyaml >=5.3
    - regex >=2022.8.17

tests:
  - python:
      imports:
        - txtai
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Build AI-powered semantic search applications
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://neuml.github.io/txtai
  repository: https://github.com/neuml/txtai

extra:
  recipe-maintainers:
    - thewchan
